consumes:
- application/json
definitions:
  Bad_Request_Response:
    properties:
      code:
        default: !!python/object/apply:http.HTTPStatus
        - 400
      error:
        default: true
      exception:
        allOf:
        - $ref: '#/definitions/Exception_Response'
        description: Message of the occurred exception.
      message:
        description: Human readable message that describes the status of the operation.
        example: 'Request not valid: two ids provided.'
        type: string
      status:
        default: Bad Request
    required:
    - message
    type: object
  Code_Request:
    properties:
      name:
        description: Code name.
        example: firewall
        type: string
      source:
        description: Code source
        type: string
    required:
    - name
    - source
    type: object
  Config_Action_Request:
    properties:
      args:
        description: Single command argument.
        example: -al
        type: string
      cmd:
        description: Command.
        type: string
      daemon:
        description: Key used to execute the command as daemon.
        example: firewall
        type: string
      id:
        description: Id of the action.
        example: start
        type: string
    required:
    - cmd
    - id
    type: object
  Config_Parameter_Request:
    properties:
      id:
        description: Id of the parameter.
        example: period
        type: string
      path:
        items:
          description: Key path.
          example: period
          type: string
        type: array
      schema:
        description: Scheme.
        enum:
        - json
        - properties
        - xml
        - yaml
        example: yaml
        type: string
      source:
        description: Source filename.
        example: firewall.xml
        type: string
      value:
        description: Parameter new value.
        example: 10s
        type: string
    required:
    - id
    - schema
    - source
    - value
    type: object
  Config_Request:
    properties:
      actions:
        description: List of actions.
        items:
          $ref: '#/definitions/Config_Action_Request'
        type: array
      parameters:
        description: List of parameters.
        items:
          $ref: '#/definitions/Config_Parameter_Request'
        type: array
      resources:
        description: List of resources.
        items:
          $ref: '#/definitions/Config_Resource_Request'
        type: array
    type: object
  Config_Resource_Request:
    properties:
      content:
        description: Resource content.
        type: string
      id:
        description: Id of the resource.
        example: filebeat-config
        type: string
      path:
        description: File path
        example: firewall.xml
        type: string
    required:
    - content
    - id
    - path
    type: object
  Exception_Response:
    properties:
      filename:
        description: Filename where the exception is raised.
        example: lib/connection.py
        type: string
      line:
        description: Line where the exception is raised.
        example: 80
        format: int32
        type: integer
      reason:
        description: Exception reason.
        example: Connection timeout
        type: string
    required:
    - filename
    - line
    - reason
    type: object
  Internal_Server_Error_Response:
    properties:
      code:
        default: !!python/object/apply:http.HTTPStatus
        - 500
      error:
        default: true
      exception:
        allOf:
        - $ref: '#/definitions/Exception_Response'
        description: Message of the occurred exception.
      message:
        description: Human readable message that describes the status of the operation.
        example: 'Request not valid: two ids provided.'
        type: string
      status:
        default: Internal Server Error
    required:
    - message
    type: object
  No_Content_Response:
    properties:
      code:
        default: !!python/object/apply:http.HTTPStatus
        - 204
      error:
        default: false
      exception:
        allOf:
        - $ref: '#/definitions/Exception_Response'
        description: Message of the occurred exception.
      message:
        description: Human readable message that describes the status of the operation.
        example: 'Request not valid: two ids provided.'
        type: string
      status:
        default: No Content
    required:
    - message
    type: object
  Not_Acceptable_Response:
    properties:
      code:
        default: !!python/object/apply:http.HTTPStatus
        - 406
      error:
        default: true
      exception:
        allOf:
        - $ref: '#/definitions/Exception_Response'
        description: Message of the occurred exception.
      message:
        description: Human readable message that describes the status of the operation.
        example: 'Request not valid: two ids provided.'
        type: string
      status:
        default: Not Acceptable
    required:
    - message
    type: object
  Ok_Response:
    properties:
      code:
        default: !!python/object/apply:http.HTTPStatus
        - 200
      error:
        default: false
      exception:
        allOf:
        - $ref: '#/definitions/Exception_Response'
        description: Message of the occurred exception.
      message:
        description: Human readable message that describes the status of the operation.
        example: 'Request not valid: two ids provided.'
        type: string
      status:
        default: OK
    required:
    - message
    type: object
  Status_Response:
    properties:
      id:
        description: ID of the execution environment.
        example: apache
        type: string
      last_heartbeat:
        description: Timestamp of the expiration of the API access configuration.
        example: 2019/02/14 15:23:33
        format: date-time
        type: string
      password:
        description: Password for the CB to connect to this LCP.
        type: string
      started:
        description: Timestamp when the LCP is started
        example: 2019/02/14 15:23:30
        format: date-time
        type: string
      username:
        description: Username for the CB to connect to this LCP.
        type: string
    required:
    - id
    - last_heartbeat
    - started
    type: object
  Unauthorized_Response:
    properties:
      code:
        default: !!python/object/apply:http.HTTPStatus
        - 401
      error:
        default: true
      exception:
        allOf:
        - $ref: '#/definitions/Exception_Response'
        description: Message of the occurred exception.
      message:
        description: Human readable message that describes the status of the operation.
        example: 'Request not valid: two ids provided.'
        type: string
      status:
        default: Unauthorized
    required:
    - message
    type: object
  Unsupported_Media_Type_Response:
    properties:
      code:
        default: !!python/object/apply:http.HTTPStatus
        - 415
      error:
        default: true
      exception:
        allOf:
        - $ref: '#/definitions/Exception_Response'
        description: Message of the occurred exception.
      message:
        description: Human readable message that describes the status of the operation.
        example: 'Request not valid: two ids provided.'
        type: string
      status:
        default: Unsupported Media Type
    required:
    - message
    type: object
info:
  title: Local Control Plane
  version: 1.1.0
paths:
  /code/{id}:
    delete:
      description: Inject code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Code_Request'
          type: array
      responses:
        '200':
          description: Codes inject correctly.
          schema:
            oneOf:
            - items: Created_Response
              type: array
        '204':
          description: No content to inject codes based on the request.
          schema:
            $ref: '#/definitions/No_Content_Response'
        '400':
          description: Request not valid.
          schema:
            $ref: '#/definitions/Bad_Request_Response'
        '401':
          description: Authentication failed.
          schema:
            $ref: '#/definitions/Unauthorized_Response'
        '406':
          description: Request validation failed.
          schema:
            $ref: '#/definitions/Not_Acceptable_Response'
        '422':
          description: Not possible to inject one or more codes.
          schema:
            items:
              oneOf:
              - Created_Response_Schema
              - Unprocessable_Entity_Response_Schema
            type: array
          500:
            description: Server not available to satisfy the request.
            schema: Internal_Server_Error_Response_Schema
      summary: Code injection
      tags:
      - code
    post:
      description: Inject code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Code_Request'
          type: array
      responses:
        '200':
          description: Codes inject correctly.
          schema:
            oneOf:
            - items: Created_Response
              type: array
        '204':
          description: No content to inject codes based on the request.
          schema:
            $ref: '#/definitions/No_Content_Response'
        '400':
          description: Request not valid.
          schema:
            $ref: '#/definitions/Bad_Request_Response'
        '401':
          description: Authentication failed.
          schema:
            $ref: '#/definitions/Unauthorized_Response'
        '406':
          description: Request validation failed.
          schema:
            $ref: '#/definitions/Not_Acceptable_Response'
        '422':
          description: Not possible to inject one or more codes.
          schema:
            items:
              oneOf:
              - Created_Response_Schema
              - Unprocessable_Entity_Response_Schema
            type: array
          500:
            description: Server not available to satisfy the request.
            schema: Internal_Server_Error_Response_Schema
      summary: Code injection
      tags:
      - code
    put:
      description: Update the injected code at run-time in the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Code_Request'
          type: array
      responses:
        '200':
          description: All injected code correctly updated.
          schema:
            items:
              $ref: '#/definitions/Ok_Response'
            type: array
        '204':
          description: No content to update codes based on the request.
          schema:
            $ref: '#/definitions/No_Content_Response'
        '304':
          description: Update for one or more codes not necessary.
          schema:
            items:
              oneOf:
              - Ok_Response_Schema
              - Not_Modified_Response
            type: array
        '400':
          description: Request not valid.
          schema:
            $ref: '#/definitions/Bad_Request_Response'
        '401':
          description: Authentication failed.
          schema:
            $ref: '#/definitions/Unauthorized_Response'
        '406':
          description: Request validation failed.
          schema:
            $ref: '#/definitions/Not_Acceptable_Response'
        '415':
          description: Media type not supported.
          schema:
            $ref: '#/definitions/Unsupported_Media_Type_Response'
        '422':
          description: Not possible to update one or more codes based on the request.
          schema:
            items:
              oneOf:
              - Ok_Response_Schema
              - Not_Modified_Response
              - Unprocessable_Entity_Response_Schema
            type: array
        '500':
          description: Server not available to satisfy the request.
          schema:
            $ref: '#/definitions/Internal_Server_Error_Response'
      summary: Update injected code
      tags:
      - code
  /config:
    post:
      description: Apply configuration changes to the local environment.
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          items:
            $ref: '#/definitions/Config_Request'
          type: array
      responses:
        '200':
          description: Configuration changed correctly.
          schema:
            oneOf:
            - items: Created_Response
              type: array
        '204':
          description: No content to configure based on the request.
          schema:
            $ref: '#/definitions/No_Content_Response'
        '400':
          description: Request not valid.
          schema:
            $ref: '#/definitions/Bad_Request_Response'
        '401':
          description: Authentication failed.
          schema:
            $ref: '#/definitions/Unauthorized_Response'
        '406':
          description: Request validation failed.
          schema:
            $ref: '#/definitions/Not_Acceptable_Response'
        '422':
          description: Not possible to change one or more configurations.
          schema:
            items:
              oneOf:
              - Created_Response_Schema
              - Unprocessable_Entity_Response_Schema
            type: array
        '500':
          description: Server not available to satisfy the request.
          schema:
            $ref: '#/definitions/Internal_Server_Error_Response'
      summary: Configuration update
      tags:
      - config
  /status:
    get:
      description: Get info about the status of the LCP in the execution environment.
      responses:
        '200':
          description: Status data of the LCP.
          schema:
            $ref: '#/definitions/Status_Response'
        '400':
          description: Request not valid.
          schema:
            $ref: '#/definitions/Bad_Request_Response'
        '401':
          description: Authentication failed.
          schema:
            $ref: '#/definitions/Unauthorized_Response'
        '406':
          description: Request validation failed.
          schema:
            $ref: '#/definitions/Not_Acceptable_Response'
        '500':
          description: Server not available to satisfy the request.
          schema:
            $ref: '#/definitions/Internal_Server_Error_Response'
      summary: Status info
      tags:
      - status
    post:
      description: Set the last heartbeat.
      responses:
        '200':
          description: Heartbeat with CB-Manager correctly executed.
          schema:
            $ref: '#/definitions/Status_Response'
        '400':
          description: Request not valid.
          schema:
            $ref: '#/definitions/Bad_Request_Response'
        '401':
          description: Authentication failed.
          schema:
            $ref: '#/definitions/Unauthorized_Response'
        '406':
          description: Request validation failed.
          schema:
            $ref: '#/definitions/Not_Acceptable_Response'
        '500':
          description: Server not available to satisfy the request.
          schema:
            $ref: '#/definitions/Internal_Server_Error_Response'
      summary: Status set.
      tags:
      - status
produces:
- application/json
swagger: '2.0'
tags:
- description: Code injection at run-time.
  name: code
- description: Configuration at run-time.
  name: config
- description: Status data of the LCP.
  name: status
